deafult: init examples

init:
	mkdir -p bin
	#cd bin; ln -s ../../lib/liblevi_interp.so . ; cd -

	
examples:
	cd ex1; make ; cd -
	cd ex2; make ; cd -
	
clean:
	cd ex1; make clean; cd -
	cd ex2; make clean; cd -

	
